# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from synus_msgs/Move_BaseGoalReq.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Move_BaseGoalReq(genpy.Message):
  _md5sum = "a183c9738f0573f138e8eff70c515846"
  _type = "synus_msgs/Move_BaseGoalReq"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int16 ReqCmd
float64 PosX
float64 PosY
float64 theta

"""
  __slots__ = ['ReqCmd','PosX','PosY','theta']
  _slot_types = ['int16','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ReqCmd,PosX,PosY,theta

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Move_BaseGoalReq, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.ReqCmd is None:
        self.ReqCmd = 0
      if self.PosX is None:
        self.PosX = 0.
      if self.PosY is None:
        self.PosY = 0.
      if self.theta is None:
        self.theta = 0.
    else:
      self.ReqCmd = 0
      self.PosX = 0.
      self.PosY = 0.
      self.theta = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_h3d().pack(_x.ReqCmd, _x.PosX, _x.PosY, _x.theta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 26
      (_x.ReqCmd, _x.PosX, _x.PosY, _x.theta,) = _get_struct_h3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_h3d().pack(_x.ReqCmd, _x.PosX, _x.PosY, _x.theta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 26
      (_x.ReqCmd, _x.PosX, _x.PosY, _x.theta,) = _get_struct_h3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_h3d = None
def _get_struct_h3d():
    global _struct_h3d
    if _struct_h3d is None:
        _struct_h3d = struct.Struct("<h3d")
    return _struct_h3d
