// Generated by gencpp from file synus_msgs/Move_BaseGoalReq.msg
// DO NOT EDIT!


#ifndef SYNUS_MSGS_MESSAGE_MOVE_BASEGOALREQ_H
#define SYNUS_MSGS_MESSAGE_MOVE_BASEGOALREQ_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace synus_msgs
{
template <class ContainerAllocator>
struct Move_BaseGoalReq_
{
  typedef Move_BaseGoalReq_<ContainerAllocator> Type;

  Move_BaseGoalReq_()
    : ReqCmd(0)
    , PosX(0.0)
    , PosY(0.0)
    , theta(0.0)  {
    }
  Move_BaseGoalReq_(const ContainerAllocator& _alloc)
    : ReqCmd(0)
    , PosX(0.0)
    , PosY(0.0)
    , theta(0.0)  {
  (void)_alloc;
    }



   typedef int16_t _ReqCmd_type;
  _ReqCmd_type ReqCmd;

   typedef double _PosX_type;
  _PosX_type PosX;

   typedef double _PosY_type;
  _PosY_type PosY;

   typedef double _theta_type;
  _theta_type theta;





  typedef boost::shared_ptr< ::synus_msgs::Move_BaseGoalReq_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::synus_msgs::Move_BaseGoalReq_<ContainerAllocator> const> ConstPtr;

}; // struct Move_BaseGoalReq_

typedef ::synus_msgs::Move_BaseGoalReq_<std::allocator<void> > Move_BaseGoalReq;

typedef boost::shared_ptr< ::synus_msgs::Move_BaseGoalReq > Move_BaseGoalReqPtr;
typedef boost::shared_ptr< ::synus_msgs::Move_BaseGoalReq const> Move_BaseGoalReqConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::synus_msgs::Move_BaseGoalReq_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::synus_msgs::Move_BaseGoalReq_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace synus_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'synus_msgs': ['/home/kbs/catkin_ws2/src/synus_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::synus_msgs::Move_BaseGoalReq_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::synus_msgs::Move_BaseGoalReq_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::synus_msgs::Move_BaseGoalReq_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::synus_msgs::Move_BaseGoalReq_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::synus_msgs::Move_BaseGoalReq_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::synus_msgs::Move_BaseGoalReq_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::synus_msgs::Move_BaseGoalReq_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a183c9738f0573f138e8eff70c515846";
  }

  static const char* value(const ::synus_msgs::Move_BaseGoalReq_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa183c9738f0573f1ULL;
  static const uint64_t static_value2 = 0x38e8eff70c515846ULL;
};

template<class ContainerAllocator>
struct DataType< ::synus_msgs::Move_BaseGoalReq_<ContainerAllocator> >
{
  static const char* value()
  {
    return "synus_msgs/Move_BaseGoalReq";
  }

  static const char* value(const ::synus_msgs::Move_BaseGoalReq_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::synus_msgs::Move_BaseGoalReq_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 ReqCmd\n\
float64 PosX\n\
float64 PosY\n\
float64 theta\n\
\n\
";
  }

  static const char* value(const ::synus_msgs::Move_BaseGoalReq_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::synus_msgs::Move_BaseGoalReq_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ReqCmd);
      stream.next(m.PosX);
      stream.next(m.PosY);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Move_BaseGoalReq_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::synus_msgs::Move_BaseGoalReq_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::synus_msgs::Move_BaseGoalReq_<ContainerAllocator>& v)
  {
    s << indent << "ReqCmd: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ReqCmd);
    s << indent << "PosX: ";
    Printer<double>::stream(s, indent + "  ", v.PosX);
    s << indent << "PosY: ";
    Printer<double>::stream(s, indent + "  ", v.PosY);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SYNUS_MSGS_MESSAGE_MOVE_BASEGOALREQ_H
