// Generated by gencpp from file synus_msgs/RobotActualPose.msg
// DO NOT EDIT!


#ifndef SYNUS_MSGS_MESSAGE_ROBOTACTUALPOSE_H
#define SYNUS_MSGS_MESSAGE_ROBOTACTUALPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace synus_msgs
{
template <class ContainerAllocator>
struct RobotActualPose_
{
  typedef RobotActualPose_<ContainerAllocator> Type;

  RobotActualPose_()
    : PosX(0.0)
    , PosY(0.0)
    , Theta(0.0)  {
    }
  RobotActualPose_(const ContainerAllocator& _alloc)
    : PosX(0.0)
    , PosY(0.0)
    , Theta(0.0)  {
  (void)_alloc;
    }



   typedef double _PosX_type;
  _PosX_type PosX;

   typedef double _PosY_type;
  _PosY_type PosY;

   typedef double _Theta_type;
  _Theta_type Theta;





  typedef boost::shared_ptr< ::synus_msgs::RobotActualPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::synus_msgs::RobotActualPose_<ContainerAllocator> const> ConstPtr;

}; // struct RobotActualPose_

typedef ::synus_msgs::RobotActualPose_<std::allocator<void> > RobotActualPose;

typedef boost::shared_ptr< ::synus_msgs::RobotActualPose > RobotActualPosePtr;
typedef boost::shared_ptr< ::synus_msgs::RobotActualPose const> RobotActualPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::synus_msgs::RobotActualPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::synus_msgs::RobotActualPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace synus_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'synus_msgs': ['/home/kbs/catkin_ws2/src/synus_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::synus_msgs::RobotActualPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::synus_msgs::RobotActualPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::synus_msgs::RobotActualPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::synus_msgs::RobotActualPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::synus_msgs::RobotActualPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::synus_msgs::RobotActualPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::synus_msgs::RobotActualPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5ac0d1ee553bd92e4acc5765f83d3dfd";
  }

  static const char* value(const ::synus_msgs::RobotActualPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5ac0d1ee553bd92eULL;
  static const uint64_t static_value2 = 0x4acc5765f83d3dfdULL;
};

template<class ContainerAllocator>
struct DataType< ::synus_msgs::RobotActualPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "synus_msgs/RobotActualPose";
  }

  static const char* value(const ::synus_msgs::RobotActualPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::synus_msgs::RobotActualPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 PosX\n\
float64 PosY\n\
float64 Theta\n\
";
  }

  static const char* value(const ::synus_msgs::RobotActualPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::synus_msgs::RobotActualPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.PosX);
      stream.next(m.PosY);
      stream.next(m.Theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotActualPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::synus_msgs::RobotActualPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::synus_msgs::RobotActualPose_<ContainerAllocator>& v)
  {
    s << indent << "PosX: ";
    Printer<double>::stream(s, indent + "  ", v.PosX);
    s << indent << "PosY: ";
    Printer<double>::stream(s, indent + "  ", v.PosY);
    s << indent << "Theta: ";
    Printer<double>::stream(s, indent + "  ", v.Theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SYNUS_MSGS_MESSAGE_ROBOTACTUALPOSE_H
