// Generated by gencpp from file synus_msgs/RosParam.msg
// DO NOT EDIT!


#ifndef SYNUS_MSGS_MESSAGE_ROSPARAM_H
#define SYNUS_MSGS_MESSAGE_ROSPARAM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace synus_msgs
{
template <class ContainerAllocator>
struct RosParam_
{
  typedef RosParam_<ContainerAllocator> Type;

  RosParam_()
    : maxvel_x(0.0)  {
    }
  RosParam_(const ContainerAllocator& _alloc)
    : maxvel_x(0.0)  {
  (void)_alloc;
    }



   typedef double _maxvel_x_type;
  _maxvel_x_type maxvel_x;





  typedef boost::shared_ptr< ::synus_msgs::RosParam_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::synus_msgs::RosParam_<ContainerAllocator> const> ConstPtr;

}; // struct RosParam_

typedef ::synus_msgs::RosParam_<std::allocator<void> > RosParam;

typedef boost::shared_ptr< ::synus_msgs::RosParam > RosParamPtr;
typedef boost::shared_ptr< ::synus_msgs::RosParam const> RosParamConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::synus_msgs::RosParam_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::synus_msgs::RosParam_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace synus_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'synus_msgs': ['/home/kbs/catkin_ws2/src/synus_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::synus_msgs::RosParam_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::synus_msgs::RosParam_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::synus_msgs::RosParam_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::synus_msgs::RosParam_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::synus_msgs::RosParam_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::synus_msgs::RosParam_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::synus_msgs::RosParam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e24297ac906b151e2564df2c9b43605e";
  }

  static const char* value(const ::synus_msgs::RosParam_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe24297ac906b151eULL;
  static const uint64_t static_value2 = 0x2564df2c9b43605eULL;
};

template<class ContainerAllocator>
struct DataType< ::synus_msgs::RosParam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "synus_msgs/RosParam";
  }

  static const char* value(const ::synus_msgs::RosParam_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::synus_msgs::RosParam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 maxvel_x\n\
";
  }

  static const char* value(const ::synus_msgs::RosParam_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::synus_msgs::RosParam_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.maxvel_x);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RosParam_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::synus_msgs::RosParam_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::synus_msgs::RosParam_<ContainerAllocator>& v)
  {
    s << indent << "maxvel_x: ";
    Printer<double>::stream(s, indent + "  ", v.maxvel_x);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SYNUS_MSGS_MESSAGE_ROSPARAM_H
